### ISSUE TITLE
Tags are case sensitive but Obsidian tags aren't

### ISSUE THREAD

**Issue by gordli** [mjsumpter/obsidian-tag-page#14]
Hi, love the plugin! Just wanted to point out that Obsidian tags are not case sensitive. However the plugin doesn't collect differently-cased tags on the same tag page. 

e.g. #park is different from #Park, and currently requires two separate tag pages to be generated.

**Comment by mjsumpter** [comment]
Oh, good call, thank you for the report! I will aim to have a fix for that out this week 🙏
