### ISSUE TITLE
Not able to populate tag page

### ISSUE THREAD

**Issue by ybalkind** [mjsumpter/obsidian-tag-page#19]
Hi

I'm able to create a tag page but I dont see how to create content within it. 

I dont see the refresh tag page button in the ribbon. So I'm unable to include lines containing the tag and/or bulleted sub-items in the tag page.

I've checked my ribbon setting and the button is showing in the settings as being included, but somehow its not there. Not sure if this is a bug or something faulty on my side. 

 Is there another way to initialize this command? I don't see it in the command palette either. 

I'm probably not doing something right with the tag page query. I've just added it as a property, but i'm presuming I should put it in a code block. If so could you please spell this out. 

Also, tag pages are being created in my vault root instead of the Tags folder.

**Comment by mjsumpter** [comment]
Hey @ybalkind - I'm not sure, but from your description it sounds like you may be using it incorrectly. The way this should work is:

- You have pages in your vault with the tag `#your-tag`
- You run the "Create tag page" action in obsidian, which will prompt you for the tag name
- When you hit enter, it should create a tag page that has all of the mentions of that tag in the rest of your vault. It should be automated, you shouldn't have to add or change anything on the generated tag page

**Comment by ybalkind** [comment]
Thanks for the feedback @mjsumpter. I only took the extra steps because the tag pages came out empty. 
But i see what went wrong. 
I was right clicking on tags in the tag pane and selecting "create tag page". That's what was throwing me off, I simply didn't bother to issue the actual command. I assumed this right click action duplicates the command but actually it creates a different kind of page in a different directory. Is that right click "create tag page" coming from your plugin? If so, it appears broken

I also got a bit thrown off by the way you handle sub-tags. I still expected that I could issue the command on a subtag directly to create its own tag page so even now when using the command I initially inputted sub-tags rather than the parent tag which failed to create a page. Perhaps just an extra line in the instructions to make that explicit.

Is it on the roadmap to enable dedicated pages for sub-tags? In my case I nest tags quite deeply and have lots of subtags used quite extensively, so having all the subtags of a given parent tag displayed on one page is too much info to be of much use. 

Otherwise I'm up and running and like what the plugin does.

**Comment by mjsumpter** [comment]
Ah okay, yeah let me make a few clarifications:

- The right click you are referring to come from the "Tag Wrangler" plugin, and is not associated with my plugin
- Your issue with sub-tags is in fact a bug. The intention is that should work, but I'll have to dig in and fix this. I created a new issue here: #20 . I'm going to close this one, but feel free to watch that issue for updates.

**Comment by ybalkind** [comment]
Ah okay, thought the right click might come from elsewhere after seeing that the command action created such a different page. Okay, sorry for the mistaken report there. Glad to hear that tag pages for sub tags is on the cards
