### ISSUE TITLE
Suggestion: Add setting to show page names instead of *

### ISSUE THREAD

**Issue by duckfarts** [mjsumpter/obsidian-tag-page#21]
Currently, tag pages create links using `[[PAGE NAME|*]]` so you just see a `*` for the link.

Is is possible to add a setting so it just shows the page name? `[[PAGE NAME]]` Otherwise, you just get a long list of identical tags with `*`s next to them, and you can't tell which one you might want to go to.

**Comment by mjsumpter** [comment]
Hey definitely, this should be an easy addition, I'll work on adding that setting.

**Comment by duckfarts** [comment]
Added this to a pull request, though that also got combined with a bugfix and other enhancement because uhh I wasn't sure how to separate them exactly.

**Comment by lsmpascal** [comment]
Hi. Great plugin.
This setting has been added or not ?
Thanks.

**Comment by lsmpascal** [comment]
Can't wait. I fixed this by deleting the |* on lines 159, 169 and 176 in myVault/.obsidian/plugins/tag-page-md/main.js
